name: adf_todo_list
description: "Projeto de To-do List da Academia do Flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  google_fonts: ^6.2.1
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.3.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
