// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3TbFtB3CQDdvsGlvHlO2E0Mn5PONDbDw',
    appId: '1:818266526767:ios:a9dc7ace2fed048d8ee2da',
    messagingSenderId: '818266526767',
    projectId: 'todo-list-adf-e8b6c',
    storageBucket: 'todo-list-adf-e8b6c.appspot.com',
    iosClientId: '818266526767-7ee7hak4dl0a5ht6reaoa6tptiiiqo14.apps.googleusercontent.com',
    iosBundleId: 'dev.helder.todo.adfTodoList',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBflv38w4l68TDsXgf5WrItXuRjRZ733kU',
    appId: '1:818266526767:android:a0636f9976f523d08ee2da',
    messagingSenderId: '818266526767',
    projectId: 'todo-list-adf-e8b6c',
    storageBucket: 'todo-list-adf-e8b6c.appspot.com',
  );

}